name: DevOps pipeline
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Python environment
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Testing
        run: |
          coverage run -m pytest
      - name: Coverage
        run: |
            coverage report
  Build:
    runs-on: ubuntu-latest
    needs:
      - Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/task-manager:${{ github.sha }}
  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.AWS_EC2_SECRET_KEY  }}" > private_key.pem
          chmod 400 private_key.pem
          ssh -o "StrictHostKeyChecking=no" -i "private_key.pem" ${{ secrets.AWS_EC2_USERNAME  }}@${{ secrets.AWS_EC2_HOSTNAME  }} ' 
          whoami
          sudo docker image rm $(sudo docker images -q)
          sudo docker kill todo
          sudo docker container rm todo
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/task-manager:${{ github.sha }}
          sudo docker run -d -p 5000:5000 --name todo ${{ secrets.DOCKER_HUB_USERNAME }}/task-manager:${{ github.sha }} '
  